/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import flagGlbUrl from '../assets/flag.glb?url'

type GLTFResult = GLTF & {
    nodes: {
        Mesh_flag: THREE.Mesh
        Mesh_flag_1: THREE.Mesh
        Mesh_flag_2: THREE.Mesh
    }
    materials: {
        woodDark: THREE.MeshStandardMaterial
        _defaultMat: THREE.MeshStandardMaterial
        heart: THREE.MeshStandardMaterial
    }
}

export const Flag = (props: JSX.IntrinsicElements['group']) => {
    const { nodes, materials } = useGLTF(flagGlbUrl) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh_flag.geometry} material={materials.woodDark} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh_flag_1.geometry} material={materials._defaultMat} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh_flag_2.geometry} material={materials.heart} />
        </group>
    )
}

useGLTF.preload(flagGlbUrl)
